Import ('Env')
Env = Env.Clone()


deplibs = [
    'glog',
    'gtest',
    'pthread',
    'gflags'
]

Env.Program('allocator_unittest', source=['allocator_unittest.cc'], LIBS=deplibs)
Env.Program('construct_unittest', source=['construct_unittest.cc'], LIBS=deplibs)
Env.Program('vector_unittest', source=['vector_unittest.cc'], LIBS=deplibs)
Env.Program('type_traits_unittest', source=['type_traits_unittest.cc'], LIBS=deplibs)
